# Generated by Django 3.2.2 on 2021-05-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreKeepers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('division', models.IntegerField(choices=[(1, 'High Advanced'), (2, 'Advanced'), (3, 'High Intermediate'), (4, 'Intermediate'), (5, 'Low Intermediate'), (6, 'Beginner')])),
                ('match_type', models.CharField(choices=[('S', 'Singles'), ('D', 'Doubles')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='doubles',
            name='playerA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doublesA', to='league.season'),
        ),
        migrations.AlterField(
            model_name='doubles',
            name='playerB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doublesB', to='league.season'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='work_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='SinglesMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league.singles')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league.singles')),
            ],
        ),
        migrations.CreateModel(
            name='SingleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.IntegerField()),
                ('away', models.IntegerField()),
                ('tie_break_home', models.IntegerField()),
                ('tie_break_away', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.singlesmatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoublesMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='league.doubles')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='league.doubles')),
            ],
        ),
        migrations.CreateModel(
            name='DoubleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.IntegerField()),
                ('away', models.IntegerField()),
                ('tie_break_home', models.IntegerField()),
                ('tie_break_away', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.doublesmatch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
