# Generated by Django 3.2.2 on 2021-05-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20210529_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorekeepers',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='league.player'),
            preserve_default=False,
        ),
    ]
