# Generated by Django 3.2.2 on 2021-07-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_scorekeepers_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='doubleset',
            name='set_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singleset',
            name='set_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doubleset',
            name='tie_break_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='doubleset',
            name='tie_break_home',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='singleset',
            name='tie_break_away',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='singleset',
            name='tie_break_home',
            field=models.IntegerField(null=True),
        ),
    ]
