# Generated by Django 3.2.2 on 2021-07-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_auto_20210725_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='doublesmatch',
            name='forfeitWin',
            field=models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='singlesmatch',
            name='forfeitWin',
            field=models.CharField(choices=[('H', 'Home'), ('A', 'Away')], max_length=1, null=True),
        ),
    ]
